apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-b5qf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0081-tenant/cin4s-839-0081-app/devfile-sample-b5qf@sha256:40bf9514dd740ef2d9136ccfdaae736dd1ef6d091ced5f3c15fc9cb4a8cd32d8
        name: my-nodejs
        resources: {}
status: {}
